name: Echo Message

on:
  push:
    branches:
      - feature/add-echo-message-workflow

jobs:
  echo-message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Echo a message
      run: echo "Hello, this is a message from GitHub Actions!"
